packages:
  - apps/*
  - packages/*
  - packages/admin-backend/domain
  - packages/admin-backend/application
  - packages/admin-backend/infrastructure

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - oxc-resolver
  - unrs-resolver
